<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Brands' => '',
    'Categories' => '',
    'Clients' => '',
    'Create' => '',
    'Create Brand' => '',
    'Create Category' => '',
    'Create Client' => '',
    'Create Employer' => '',
    'Create Product' => '',
    'Create Product Brand' => '',
    'Create Product Category' => '',
    'Create Related Articles' => '',
    'Delete' => '',
    'Email' => '',
    'Employers' => '',
    'Password' => '',
    'Please fill out the following fields to create a new user:' => '',
    'Product Brands' => '',
    'Product Categories' => '',
    'Products' => '',
    'Register' => '',
    'Related Articles' => '',
    'Reset' => '',
    'Rol' => '',
    'Save changes' => '',
    'Search' => '',
    'Sign In' => '',
    'Sign in to start your session' => '',
    'This email address has already been taken.' => '',
    'This username has already been taken.' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Username' => '',
];
