<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assign a Zone' => '',
    'Available clients' => '',
    'Avatar' => '',
    'Category' => '',
    'Client Wallets' => '',
    'Client updated' => '',
    'Clients' => '',
    'Create Client' => '',
    'Create Client Wallet' => '',
    'Create Employer' => '',
    'Create Related Articles' => '',
    'Create Zone' => '',
    'Don´t has second phone' => '',
    'Email' => 'Correo',
    'Employer updated' => '',
    'Employers' => 'Empleados',
    'Invalid user' => '',
    'Password' => '',
    'Please fill out the following fields to create a new user:' => '',
    'Please select a role' => '',
    'Product' => '',
    'Profile' => '',
    'Register' => '',
    'Related Articles' => '',
    'Rol' => '',
    'Save changes' => '',
    'Sign In' => '',
    'This email address has already been taken.' => '',
    'This username has already been taken.' => '',
    'Upload Image' => '',
    'User updated' => '',
    'Username' => 'Usuario',
    'Zones' => 'Zonas',
    'Create Product Brand' => 'Crear Producto Marca',
    'Name' => 'Nombre',
    'Product Brands' => 'Producto Marcas',
    'Are you sure you want to delete this item?' => '¿Desea eliminar este registro?',
    'Brands' => 'Marcas',
    'Description' => 'Descripción',
    'Categories' => 'Categorías',
    'Create' => 'Crear',
    'Create Brand' => 'Crear Marca',
    'Create Category' => 'Crear Categoría',
    'Create Product' => 'Crear Producto',
    'Create Product Category' => 'Crear Producto Categoría',
    'Delete' => 'Borrar',
    'Product Categories' => 'Producto Categorías',
    'Products' => 'Productos',
    'Reset' => 'Reiniciar',
    'Search' => 'Buscar',
    'Sign in to start your session' => 'Inicia sesión para comenzar',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizando: ',
];
