<?php
/**
 * Created by PhpStorm.
 * User: Hugo
 * Date: 24/12/2016
 * Time: 12:03 PM
 */

namespace api\modules\v1\models;

use common\models\User;
use yii\helpers\ArrayHelper;

class UserAPI extends User
{
    /**
     * @inheritdoc
     */
    public function fields()
    {
        $fields = parent::fields(); // TODO: Change the autogenerated stub
        unset($fields['auth_key'], $fields['password_hash'], $fields['password_reset_token']);

        return $fields;
    }

    /**
     * @inheritdoc
     */
    public function extraFields()
    {
        return [
            'employer'
        ];
    }
}