<?php
/**
 * Created by PhpStorm.
 * User: Hugo
 * Date: 24/12/2016
 * Time: 12:51 PM
 */

namespace api\modules\v1\controllers;

use common\models\ClientWallet;
use yii\filters\auth\QueryParamAuth;
use yii\rest\ActiveController;

class ClientWalletController extends ActiveController
{
    public $modelClass = 'common\models\ClientWallet';

    /**
     * @inheritdoc
     */
    public function actions()
    {
        $actions = parent::actions();
        unset($actions['create'], $actions['update'], $actions['delete'], $actions['index'], $actions['view']);

        return $actions;
    }

    public function actionIndex($employer_id)
    {
        /* @var $modelClass \common\models\ClientWallet */
        $modelClass = $this->modelClass;
       return $modelClass::findAll(['employer_id' => $employer_id]);
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors =  parent::behaviors();

        $behaviors['authenticator'] = [
            'class' => QueryParamAuth::className(),
        ];
        return $behaviors;
    }

    public function checkAccess($action, $model = null, $params = [])
    {
        parent::checkAccess($action, $model, $params); // TODO: Change the autogenerated stub
    }
}