<?php
/**
 * Created by PhpStorm.
 * User: Hugo
 * Date: 24/01/2017
 * Time: 9:54 PM
 */

namespace api\modules\v1\controllers;

use yii\filters\auth\QueryParamAuth;
use yii\rest\ActiveController;

class EnterpriseController extends ActiveController
{
    public $modelClass = 'common\models\Enterprise';

    /**
     * @inheritdoc
     */
    public function actions()
    {
        $actions = parent::actions();
        unset($actions['create'], $actions['update'], $actions['delete'], $actions['index'], $actions['view']);

        return $actions;
    }

    public function actionIndex()
    {
        /* @var $modelClass \common\models\Enterprise */
        $modelClass = $this->modelClass;
        return $modelClass::findOne(1);
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors =  parent::behaviors();

        $behaviors['authenticator'] = [
            'class' => QueryParamAuth::className(),
        ];
        return $behaviors;
    }

    public function checkAccess($action, $model = null, $params = [])
    {
        parent::checkAccess($action, $model, $params); // TODO: Change the autogenerated stub
    }
}