<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => '',
    'Assigned' => '',
    'Avatar' => '',
    'Brand' => '',
    'Child Article' => '',
    'Client ID' => '',
    'Client Wallet ID' => '',
    'Code' => '',
    'Created At' => '',
    'Credit Limit' => '',
    'Description' => '',
    'Email' => '',
    'Employer ID' => '',
    'Founded Date' => '',
    'Fullname' => '',
    'ID' => '',
    'Identification' => '',
    'Lastname' => '',
    'Lat' => '',
    'Lng' => '',
    'Name' => '',
    'Order ID' => '',
    'Parent Article' => '',
    'Password' => '',
    'Path' => '',
    'Phone' => '',
    'Phone1' => '',
    'Phone2' => '',
    'Price' => '',
    'Product' => '',
    'Product ID' => '',
    'Product Images' => '',
    'Quantity' => '',
    'Remember Me' => '',
    'Repeat Password' => '',
    'Rif' => '',
    'Rol' => '',
    'Status' => '',
    'Tag' => '',
    'This email address has already been taken.' => '',
    'This username has already been taken.' => '',
    'Type' => '',
    'Updated At' => '',
    'Updated By' => '',
    'User' => '',
    'User ID' => '',
    'Username' => '',
    'Zone' => '',
    'active' => '',
    'inactive' => '',
    'Brand ID' => '@@@@',
    'Category ID' => '@@@@',
    'Child' => '@@@@',
    'Credit Use' => '@@@@',
    'Parent' => '@@@@',
];
