<?php
/**
 * Created by PhpStorm.
 * User: Hugo
 * Date: 06/02/2017
 * Time: 7:15 PM
 */

namespace backend\models;

use Yii;
use yii\base\Model;

class DateTimeModel extends Model
{
    public $since;
    public $to;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if(!$this->since)
            $this->since = '2016-12-12 10:00';
        if(!$this->to)
            $this->to = Date("Y-m-d h:m");
    }

    public function rules()
    {
        return [
            [['since', 'to'], 'datetime']
        ];
    }

    public function attributeLabels()
    {
        return [
            'since' => Yii::t('backend', 'Since'),
            'to' => Yii::t('backend', 'To')
        ];
    }
}