<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => 'Dirección',
    'Assigned' => 'Asignado',
    'Avatar' => 'Avatar',
    'Brand' => 'Marca',
    'Child Article' => 'Artículo Hijo',
    'Client ID' => 'Cliente',
    'Client Wallet ID' => 'Cartera de Cliente',
    'Code' => 'Código',
    'Created At' => 'Creado a las',
    'Credit Limit' => 'Límite de Crédito',
    'Credit Use' => 'Crédito Consumido',
    'Description' => 'Descripción',
    'Email' => 'Correo',
    'Employer ID' => 'Empleado',
    'Fullname' => 'Nombre Completo',
    'ID' => 'ID',
    'Identification' => 'Indentificación',
    'Lastname' => 'Apellido',
    'Lat' => 'Latitud',
    'Lng' => 'Longitud',
    'Order ID' => 'Orden',
    'Parent Article' => 'Artículo Padre',
    'Password' => 'Contraseña',
    'Path' => 'Ubicación',
    'Phone1' => 'Teléfono 1',
    'Phone2' => 'Teléfono 2',
    'Price' => 'Precio',
    'Product' => 'Producto',
    'Product ID' => 'Producto',
    'Product Images' => 'Imagen del Producto',
    'Quantity' => 'Cantidad',
    'Rol' => 'Rol',
    'Status' => 'Estado',
    'Tag' => 'Etiqueta',
    'This email address has already been taken.' => 'El correo está siendo utilizado',
    'This username has already been taken.' => 'El nombre de usuario esta siendo utilizado',
    'Type' => 'Tipo',
    'Updated At' => 'Actualización',
    'Updated By' => 'Actualizado por',
    'User' => 'Usuario',
    'User ID' => 'Usuario',
    'Username' => 'Nombre de Usuario',
    'Zone' => 'Zona',
    'active' => 'Activo',
    'inactive' => 'Inactivo',
    'Brand ID' => 'Marca',
    'Category ID' => 'Categoría',
    'Child' => 'Hijo',
    'Parent' => 'Padre',
    'Name' => 'Nombre',
];
